# Generated by Django 4.2.3 on 2023-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='status',
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='aparelho',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='marca',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemdeservico',
            name='numero_serie',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
